// VidiaForge — Storage Provider abstraction
// Pluggable interface for local filesystem + S3-compatible object storage (R2/S3/MinIO).
// All paths are RELATIVE keys inside the storage root — never hardcode absolute paths.

/**
 * UploadUrlInput — parameters for `createUploadUrl()`.
 *
 * V4-S1: `maxSizeBytes` was RENAMED to `contentLength` because the previous
 * implementation signed a presigned URL with `ContentLength: 500MB` for EVERY
 * upload regardless of actual file size. That means a 1MB upload would be
 * rejected by S3 (request body smaller than the signed ContentLength) and a
 * 600MB upload would silently succeed (allowing users to exceed the cap).
 *
 * `contentLength` MUST be the ACTUAL file size in bytes — callers are
 * responsible for validating it against MAX_UPLOAD_BYTES before invoking.
 */
export interface UploadUrlInput {
  /** Storage key (relative path inside the bucket / upload dir), e.g. "uploads/abc.mp4" */
  key: string;
  /** Expected MIME type */
  contentType: string;
  /** ACTUAL file size in bytes (NOT a max). Signed into the presigned URL so S3
   *  rejects uploads whose body length doesn't match — closes the P0 hole where
   *  every upload was signed for 500MB regardless of true size. */
  contentLength: number;
  /** URL expiration in seconds (presigned URLs only) */
  expiresIn?: number;
}

export interface UploadUrlResult {
  /** The URL the client should PUT/POST the file to */
  url: string;
  /** HTTP method the client must use */
  method: 'PUT' | 'POST';
  /** Required headers (e.g. Content-Type, x-amz-* for S3) */
  headers?: Record<string, string>;
  /** Echoes the key */
  key: string;
  /** Expiration in seconds */
  expiresIn: number;
}

export interface DownloadUrlInput {
  /** Storage key */
  key: string;
  /** URL expiration in seconds (presigned URLs only) */
  expiresIn?: number;
}

export interface PutObjectInput {
  /** Storage key */
  key: string;
  /** File body — Buffer for small files, ReadableStream for large */
  body: Buffer | ReadableStream<Uint8Array>;
  /** MIME type */
  contentType: string;
}

export interface GetObjectInput {
  /** Storage key */
  key: string;
  /** Optional byte range (inclusive, 0-indexed) for partial reads */
  range?: { start: number; end: number };
}

export interface PutObjectResult {
  key: string;
}

/**
 * StorageObjectMetadata — result of `headObject()`.
 *
 * V4-S1: added so the finalize endpoint can verify (a) the object actually
 * exists in storage and (b) its real size matches the UploadIntent.expectedSize
 * before creating the MediaAsset row. Previously the pipeline trusted the
 * client-supplied `size` field verbatim — an attacker could upload a 1-byte
 * file to S3 then finalize with `size: 500000000` to bypass the upload cap.
 */
export interface StorageObjectMetadata {
  /** Storage key (echoes the input) */
  key: string;
  /** Object size in bytes */
  size: number;
  /** MIME type if known */
  contentType?: string;
  /** ETag (S3) or undefined (local) */
  etag?: string;
  /** Last-modified timestamp */
  lastModified?: Date;
}

/**
 * StorageProvider — abstracts local FS vs. S3/R2.
 * Implementations MUST be honest about their capabilities:
 *  - LocalStorageProvider.getPublicUrl returns null (local files aren't public).
 *  - S3 provider throws on missing credentials, never silently no-ops.
 */
export interface StorageProvider {
  /** Provider identifier for health checks + logging */
  readonly name: 'local' | 's3' | 'r2';

  /**
   * Returns either:
   *   - Local: a JWT-signed URL pointing to /api/assets/upload-direct (the API handles the upload)
   *   - S3/R2: a real presigned PUT URL the client uploads to directly
   */
  createUploadUrl(input: UploadUrlInput): Promise<UploadUrlResult>;

  /**
   * Returns either:
   *   - Local: a relative URL "/api/assets/{key}" the API Range-streams
   *   - S3/R2: a real presigned GET URL
   */
  createDownloadUrl(input: DownloadUrlInput): Promise<string>;

  /** Server-side direct upload (small files / thumbnails / proxy media generated by workers) */
  putObject(input: PutObjectInput): Promise<PutObjectResult>;

  /**
   * Server-side fetch. Returns a web ReadableStream (preferred) or Buffer.
   * Honors range if the underlying store supports it.
   */
  getObject(input: GetObjectInput): Promise<ReadableStream<Uint8Array> | Buffer>;

  /**
   * STREAMING upload — accepts a ReadableStream (web) or NodeJS.ReadableStream
   * and uploads it WITHOUT buffering the entire body into memory. This is the
   * CRITICAL method for large files (rendered videos, proxies) — the existing
   * `putObject` is fine for small payloads (thumbnails, waveforms) but must
   * not be used for large media because it drains the stream into a Buffer
   * before sending, which causes OOM on multi-hundred-MB outputs.
   *
   * For local FS: pipes the stream into a fs.WriteStream.
   * For S3/R2: uses @aws-sdk/lib-storage's Upload (multipart, 5+ MB parts).
   */
  uploadStream(
    key: string,
    stream: ReadableStream<Uint8Array> | NodeJS.ReadableStream,
    metadata?: { contentType?: string; contentLength?: number }
  ): Promise<{ key: string }>;

  /**
   * STREAMING download — returns a web ReadableStream. Honors an optional
   * byte range. Equivalent to `getObject` but always streams (never returns
   * a pre-buffered Buffer) and is the preferred API for large media.
   */
  getObjectStream(key: string, range?: { start: number; end: number }): Promise<ReadableStream<Uint8Array>>;

  /**
   * HEAD object — fetch metadata WITHOUT downloading the body.
   *
   * V4-S1: used by /api/assets/finalize to verify the uploaded object exists
   * and that its actual size matches the UploadIntent.expectedSize before
   * creating a MediaAsset row. Returns `null` if the object doesn't exist
   * (local: ENOENT; S3: NoSuchKey / 404). Implementations MUST NOT throw on
   * missing object — only on transport errors (auth, network, etc.).
   */
  headObject(key: string): Promise<StorageObjectMetadata | null>;

  /** Delete a stored object. Best-effort (no throw on missing). */
  deleteObject(key: string): Promise<void>;

  /** True if the object exists */
  objectExists(key: string): Promise<boolean>;

  /**
   * Public URL for an object, or null if the provider doesn't expose public URLs.
   * Local FS returns null. S3 returns the bucket public URL only if STORAGE_PUBLIC_BASE_URL is set.
   */
  getPublicUrl(key: string): string | null;

  /**
   * V7 §33: Perform a safe authorized operation to verify the provider's
   * credentials actually work. This is the REAL storage readiness check —
   * not just "is the provider configured" but "can we actually access the bucket".
   *
   * For S3/R2: equivalent to HeadBucket.
   * For local: verifies the upload directory exists + is writable.
   *
   * Returns true if the provider is accessible, false otherwise.
   * NEVER throws — callers should use the return value to decide readiness.
   */
  checkHealth(): Promise<boolean>;
}
