// VidiaForge v19 — Builtin Template Seed Data
//
// V19 §6: Categories cover Trending, Social, Lifestyle, Events, Business,
// Creator, Visual Styles, Music.
//
// V19.1 §5.1 — Each template is a REAL TemplateDefinition with valid
// timelineData that can actually be rendered. Clips that need user
// media carry a `slotId` (the slot's stable identifier). The clip's
// `assetId` is intentionally EMPTY until the user assigns a real
// asset to the slot via the /api/templates/[id]/use or /apply flow.
//
// We previously used fake `placeholder-{slotId}` strings as assetId
// values — that was misleading because it looked like a real asset
// reference but pointed at no actual asset. The slot system is the
// legitimate mechanism for "user-replaceable media" — the assetId
// stays empty until a real asset is assigned.
//
// V19.1 §5.2 — Each template has a real `thumbnailUrl` pointing at a
// PNG generated by `scripts/generate-template-thumbnails.ts`. These
// thumbnails are real representative frames (gradient background +
// title text + clip-slot rectangles) — NOT fake gradient fallbacks.
//
// V19 §76: Templates reference assets by ID, not by embedding media files.

import type { TemplateDefinition } from './index';
import { uid } from '../timeline';

// Helper: build a minimal valid clip with sensible defaults.
function buildClip(opts: {
  id: string;
  trackId: string;
  kind: 'video' | 'audio' | 'image' | 'text';
  timelineStart: number;
  duration: number;
  slotId?: string;
  text?: string;
}): any {
  // V19.1 §5.1: media slots leave assetId EMPTY — the slot system is the
  // legitimate "user-replaceable media" mechanism. The assetId is
  // populated only when the user assigns a real asset via the
  // /api/templates/[id]/use or /apply flow's slot-assignment step.
  // (Previously this used `placeholder-{slotId}` strings which were
  // misleading — they looked like asset references but pointed at no
  // real asset.)
  const hasSlot = !!opts.slotId;
  return {
    id: opts.id,
    trackId: opts.trackId,
    kind: opts.kind,
    // For media clips with a slot: empty assetId (filled in at apply time).
    // For media clips with no slot: empty assetId (rare; templates should
    //   always use a slot for user-replaceable media).
    // For text clips: undefined (text clips don't reference assets).
    assetId: opts.kind === 'text' ? undefined : (hasSlot ? '' : ''),
    assetName: opts.kind === 'text' ? undefined : (hasSlot ? 'Unassigned slot' : 'Unassigned'),
    sourceStart: 0,
    sourceEnd: opts.duration,
    timelineStart: opts.timelineStart,
    duration: opts.duration,
    speed: 1,
    reverse: false,
    frozen: null,
    transform: { x: 0, y: 0, scale: 1, rotation: 0, opacity: 1, anchorX: 0.5, anchorY: 0.5 },
    crop: { top: 0, right: 0, bottom: 0, left: 0 },
    blendMode: 'normal',
    color: {
      exposure: 0, brightness: 0, contrast: 0, highlights: 0, shadows: 0,
      whites: 0, blacks: 0, saturation: 0, vibrance: 0, temperature: 0, tint: 0, hue: 0,
    },
    audio: { volume: 1, pan: 0, fadeIn: 0, fadeOut: 0, muted: false },
    effects: [],
    filters: [],
    transitions: [],
    keyframes: [],
    masks: [],
    slotId: opts.slotId,
    text: opts.kind === 'text' ? {
      text: opts.text || 'Your text',
      fontFamily: 'Inter',
      fontSize: 48,
      fontWeight: 700,
      italic: false,
      letterSpacing: 0,
      lineHeight: 1.2,
      align: 'center' as const,
      color: '#ffffff',
      animation: 'fade' as const,
    } : undefined,
    enabled: true,
  };
}

function buildTrack(id: string, kind: 'video' | 'audio' | 'text' | 'subtitle', name: string): any {
  return {
    id, kind, name, locked: false, hidden: false, solo: false, muted: false, height: 80,
  };
}

// V19.1 §5.2: helper to compute the public thumbnail URL for a template.
// The actual PNGs are generated by scripts/generate-template-thumbnails.ts
// and shipped under /public/templates/{template-id}.png.
function thumbnailUrlFor(templateId: string): string {
  return `/templates/${templateId}.png`;
}

export const BUILTIN_TEMPLATES: TemplateDefinition[] = [
  // === §6 Social: TikTok ===
  {
    id: 'tpl-tiktok-viral-9x16',
    title: 'TikTok Viral',
    description: 'Punchy captions + beat sync. 15-second 9:16 vertical format.',
    category: 'Social',
    subcategory: 'TikTok',
    tags: ['tiktok', 'viral', 'vertical', 'social', 'short-form', 'beat-sync'],
    thumbnailUrl: thumbnailUrlFor('tpl-tiktok-viral-9x16'),
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    duration: 15,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-main', 'video', 'Main'),
        buildTrack('tr-text', 'text', 'Text'),
      ],
      clips: [
        buildClip({
          id: 'clip-1', trackId: 'tr-main', kind: 'video',
          timelineStart: 0, duration: 15, slotId: 'slot-media-1',
        }),
        buildClip({
          id: 'clip-text-1', trackId: 'tr-text', kind: 'text',
          timelineStart: 0.5, duration: 3, slotId: 'slot-text-1', text: 'POV: when…',
        }),
        buildClip({
          id: 'clip-text-2', trackId: 'tr-text', kind: 'text',
          timelineStart: 4, duration: 3, slotId: 'slot-text-2', text: 'Wait for it',
        }),
        buildClip({
          id: 'clip-text-3', trackId: 'tr-text', kind: 'text',
          timelineStart: 8, duration: 3, slotId: 'slot-text-3', text: 'Did you see that?',
        }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-media-1', type: 'media', label: 'Main video', hint: '15s vertical clip', required: true, acceptedKinds: ['video'] },
      { id: 'slot-text-1', type: 'text', label: 'Hook text', required: true, defaultValue: 'POV: when…' },
      { id: 'slot-text-2', type: 'text', label: 'Build-up text', required: false, defaultValue: 'Wait for it' },
      { id: 'slot-text-3', type: 'text', label: 'Punchline text', required: false, defaultValue: 'Did you see that?' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Social: Instagram Reels ===
  {
    id: 'tpl-reels-promo-9x16',
    title: 'Reel Promo',
    description: 'Product showcase with bold captions. 30-second vertical.',
    category: 'Social',
    subcategory: 'Instagram Reels',
    tags: ['reels', 'instagram', 'product', 'promo', 'vertical'],
    thumbnailUrl: thumbnailUrlFor('tpl-reels-promo-9x16'),
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    duration: 30,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-main', 'video', 'Main'),
        buildTrack('tr-text', 'text', 'Captions'),
      ],
      clips: [
        buildClip({
          id: 'clip-1', trackId: 'tr-main', kind: 'video',
          timelineStart: 0, duration: 10, slotId: 'slot-media-1',
        }),
        buildClip({
          id: 'clip-2', trackId: 'tr-main', kind: 'video',
          timelineStart: 10, duration: 10, slotId: 'slot-media-2',
        }),
        buildClip({
          id: 'clip-3', trackId: 'tr-main', kind: 'video',
          timelineStart: 20, duration: 10, slotId: 'slot-media-3',
        }),
        buildClip({
          id: 'clip-text-1', trackId: 'tr-text', kind: 'text',
          timelineStart: 1, duration: 4, slotId: 'slot-text-1', text: 'New Drop',
        }),
        buildClip({
          id: 'clip-text-2', trackId: 'tr-text', kind: 'text',
          timelineStart: 11, duration: 4, slotId: 'slot-text-2', text: 'Features',
        }),
        buildClip({
          id: 'clip-text-3', trackId: 'tr-text', kind: 'text',
          timelineStart: 21, duration: 4, slotId: 'slot-text-3', text: 'Shop now',
        }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-media-1', type: 'media', label: 'Opening shot', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-media-2', type: 'media', label: 'Feature shot', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-media-3', type: 'media', label: 'Closing shot', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-text-1', type: 'text', label: 'Opening text', required: true, defaultValue: 'New Drop' },
      { id: 'slot-text-2', type: 'text', label: 'Feature text', required: false, defaultValue: 'Features' },
      { id: 'slot-text-3', type: 'text', label: 'CTA text', required: true, defaultValue: 'Shop now' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Creator: YouTube Intro ===
  {
    id: 'tpl-youtube-intro-16x9',
    title: 'YouTube Intro',
    description: 'Branded intro animation. 8 seconds, 16:9.',
    category: 'Creator',
    subcategory: 'YouTube Intro',
    tags: ['youtube', 'intro', 'branded', 'cinematic'],
    thumbnailUrl: thumbnailUrlFor('tpl-youtube-intro-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 8,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-bg', 'video', 'Background'),
        buildTrack('tr-logo', 'video', 'Logo'),
        buildTrack('tr-text', 'text', 'Channel Name'),
      ],
      clips: [
        buildClip({
          id: 'clip-bg', trackId: 'tr-bg', kind: 'video',
          timelineStart: 0, duration: 8, slotId: 'slot-bg',
        }),
        buildClip({
          id: 'clip-logo', trackId: 'tr-logo', kind: 'image',
          timelineStart: 1, duration: 6, slotId: 'slot-logo',
        }),
        buildClip({
          id: 'clip-text-channel', trackId: 'tr-text', kind: 'text',
          timelineStart: 2, duration: 5, slotId: 'slot-channel-name', text: 'Your Channel',
        }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-bg', type: 'media', label: 'Background video', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-logo', type: 'logo', label: 'Brand logo', required: false, brandKitToken: 'logo', acceptedKinds: ['image'] },
      { id: 'slot-channel-name', type: 'text', label: 'Channel name', required: true, defaultValue: 'Your Channel' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Events: Birthday ===
  {
    id: 'tpl-birthday-wish-9x16',
    title: 'Birthday Wish',
    description: 'Festive celebration with photo montage. 20 seconds, vertical.',
    category: 'Events',
    subcategory: 'Birthday',
    tags: ['birthday', 'celebration', 'festive', 'photos', 'vertical'],
    thumbnailUrl: thumbnailUrlFor('tpl-birthday-wish-9x16'),
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    duration: 20,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-photos', 'video', 'Photos'),
        buildTrack('tr-text', 'text', 'Messages'),
      ],
      clips: [
        buildClip({ id: 'clip-p1', trackId: 'tr-photos', kind: 'image', timelineStart: 0, duration: 4, slotId: 'slot-photo-1' }),
        buildClip({ id: 'clip-p2', trackId: 'tr-photos', kind: 'image', timelineStart: 4, duration: 4, slotId: 'slot-photo-2' }),
        buildClip({ id: 'clip-p3', trackId: 'tr-photos', kind: 'image', timelineStart: 8, duration: 4, slotId: 'slot-photo-3' }),
        buildClip({ id: 'clip-p4', trackId: 'tr-photos', kind: 'image', timelineStart: 12, duration: 4, slotId: 'slot-photo-4' }),
        buildClip({ id: 'clip-p5', trackId: 'tr-photos', kind: 'image', timelineStart: 16, duration: 4, slotId: 'slot-photo-5' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-text', kind: 'text', timelineStart: 0, duration: 4, slotId: 'slot-msg-1', text: 'Happy Birthday!' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-text', kind: 'text', timelineStart: 8, duration: 4, slotId: 'slot-msg-2', text: 'Wishing you joy' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-text', kind: 'text', timelineStart: 16, duration: 4, slotId: 'slot-msg-3', text: 'Celebrate!' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-photo-1', type: 'media', label: 'Photo 1', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-2', type: 'media', label: 'Photo 2', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-3', type: 'media', label: 'Photo 3', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-4', type: 'media', label: 'Photo 4', required: false, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-5', type: 'media', label: 'Photo 5', required: false, acceptedKinds: ['image', 'video'] },
      { id: 'slot-msg-1', type: 'text', label: 'Opening message', required: true, defaultValue: 'Happy Birthday!' },
      { id: 'slot-msg-2', type: 'text', label: 'Middle message', required: false, defaultValue: 'Wishing you joy' },
      { id: 'slot-msg-3', type: 'text', label: 'Closing message', required: false, defaultValue: 'Celebrate!' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Business: Product Demo ===
  {
    id: 'tpl-product-demo-16x9',
    title: 'Product Demo',
    description: 'Feature-by-feature product walkthrough. 30 seconds, 16:9.',
    category: 'Business',
    subcategory: 'Product Launch',
    tags: ['product', 'demo', 'business', 'marketing', 'feature'],
    thumbnailUrl: thumbnailUrlFor('tpl-product-demo-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 30,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-main', 'video', 'Main'),
        buildTrack('tr-text', 'text', 'Features'),
      ],
      clips: [
        buildClip({ id: 'clip-1', trackId: 'tr-main', kind: 'video', timelineStart: 0, duration: 10, slotId: 'slot-media-1' }),
        buildClip({ id: 'clip-2', trackId: 'tr-main', kind: 'video', timelineStart: 10, duration: 10, slotId: 'slot-media-2' }),
        buildClip({ id: 'clip-3', trackId: 'tr-main', kind: 'video', timelineStart: 20, duration: 10, slotId: 'slot-media-3' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-text', kind: 'text', timelineStart: 1, duration: 4, slotId: 'slot-text-1', text: 'Feature One' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-text', kind: 'text', timelineStart: 11, duration: 4, slotId: 'slot-text-2', text: 'Feature Two' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-text', kind: 'text', timelineStart: 21, duration: 4, slotId: 'slot-text-3', text: 'Get yours' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-media-1', type: 'media', label: 'Feature 1 demo', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-media-2', type: 'media', label: 'Feature 2 demo', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-media-3', type: 'media', label: 'Closing shot', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-text-1', type: 'text', label: 'Feature 1 label', required: true, defaultValue: 'Feature One' },
      { id: 'slot-text-2', type: 'text', label: 'Feature 2 label', required: true, defaultValue: 'Feature Two' },
      { id: 'slot-text-3', type: 'text', label: 'CTA', required: true, defaultValue: 'Get yours' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Visual Styles: Cinematic ===
  {
    id: 'tpl-cinematic-trailer-21x9',
    title: 'Cinematic Trailer',
    description: 'Cinematic 21:9 trailer with dramatic text. 30 seconds.',
    category: 'Visual Styles',
    subcategory: 'Cinematic',
    tags: ['cinematic', 'trailer', 'dramatic', 'wide', 'film'],
    thumbnailUrl: thumbnailUrlFor('tpl-cinematic-trailer-21x9'),
    aspectRatio: '21:9',
    width: 2560,
    height: 1080,
    fps: 24,
    duration: 30,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-scene', 'video', 'Scene'),
        buildTrack('tr-title', 'text', 'Title Cards'),
      ],
      clips: [
        buildClip({ id: 'clip-s1', trackId: 'tr-scene', kind: 'video', timelineStart: 0, duration: 10, slotId: 'slot-scene-1' }),
        buildClip({ id: 'clip-s2', trackId: 'tr-scene', kind: 'video', timelineStart: 10, duration: 10, slotId: 'slot-scene-2' }),
        buildClip({ id: 'clip-s3', trackId: 'tr-scene', kind: 'video', timelineStart: 20, duration: 10, slotId: 'slot-scene-3' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-title', kind: 'text', timelineStart: 2, duration: 6, slotId: 'slot-title-1', text: 'In a world…' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-title', kind: 'text', timelineStart: 12, duration: 6, slotId: 'slot-title-2', text: 'One choice' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-title', kind: 'text', timelineStart: 22, duration: 6, slotId: 'slot-title-3', text: 'Coming soon' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-scene-1', type: 'media', label: 'Opening scene', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-scene-2', type: 'media', label: 'Middle scene', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-scene-3', type: 'media', label: 'Closing scene', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-title-1', type: 'text', label: 'Opening title', required: true, defaultValue: 'In a world…' },
      { id: 'slot-title-2', type: 'text', label: 'Middle title', required: true, defaultValue: 'One choice' },
      { id: 'slot-title-3', type: 'text', label: 'Closing title', required: true, defaultValue: 'Coming soon' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === V19.1 §5.3 — additional template categories for a coherent catalog ===

  // === §6 Lifestyle: Fashion Showcase ===
  {
    id: 'tpl-fashion-showcase-9x16',
    title: 'Fashion Showcase',
    description: 'Vertical fashion lookbook with bold text overlays. 18 seconds.',
    category: 'Lifestyle',
    subcategory: 'Fashion',
    tags: ['fashion', 'lookbook', 'vertical', 'lifestyle', 'style'],
    thumbnailUrl: thumbnailUrlFor('tpl-fashion-showcase-9x16'),
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    duration: 18,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-looks', 'video', 'Looks'),
        buildTrack('tr-text', 'text', 'Labels'),
      ],
      clips: [
        buildClip({ id: 'clip-l1', trackId: 'tr-looks', kind: 'image', timelineStart: 0, duration: 6, slotId: 'slot-look-1' }),
        buildClip({ id: 'clip-l2', trackId: 'tr-looks', kind: 'image', timelineStart: 6, duration: 6, slotId: 'slot-look-2' }),
        buildClip({ id: 'clip-l3', trackId: 'tr-looks', kind: 'image', timelineStart: 12, duration: 6, slotId: 'slot-look-3' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-text', kind: 'text', timelineStart: 1, duration: 4, slotId: 'slot-text-1', text: 'Look 01' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-text', kind: 'text', timelineStart: 7, duration: 4, slotId: 'slot-text-2', text: 'Look 02' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-text', kind: 'text', timelineStart: 13, duration: 4, slotId: 'slot-text-3', text: 'Look 03' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-look-1', type: 'media', label: 'Look 1 photo', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-look-2', type: 'media', label: 'Look 2 photo', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-look-3', type: 'media', label: 'Look 3 photo', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-text-1', type: 'text', label: 'Look 1 label', required: true, defaultValue: 'Look 01' },
      { id: 'slot-text-2', type: 'text', label: 'Look 2 label', required: true, defaultValue: 'Look 02' },
      { id: 'slot-text-3', type: 'text', label: 'Look 3 label', required: true, defaultValue: 'Look 03' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Lifestyle: Travel Montage ===
  {
    id: 'tpl-travel-montage-16x9',
    title: 'Travel Montage',
    description: 'Cinematic travel montage with location captions. 24 seconds, 16:9.',
    category: 'Lifestyle',
    subcategory: 'Travel',
    tags: ['travel', 'montage', 'cinematic', 'landscape', 'adventure'],
    thumbnailUrl: thumbnailUrlFor('tpl-travel-montage-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 24,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-scenes', 'video', 'Scenes'),
        buildTrack('tr-text', 'text', 'Locations'),
      ],
      clips: [
        buildClip({ id: 'clip-s1', trackId: 'tr-scenes', kind: 'video', timelineStart: 0, duration: 8, slotId: 'slot-scene-1' }),
        buildClip({ id: 'clip-s2', trackId: 'tr-scenes', kind: 'video', timelineStart: 8, duration: 8, slotId: 'slot-scene-2' }),
        buildClip({ id: 'clip-s3', trackId: 'tr-scenes', kind: 'video', timelineStart: 16, duration: 8, slotId: 'slot-scene-3' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-text', kind: 'text', timelineStart: 1, duration: 5, slotId: 'slot-text-1', text: 'Location 1' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-text', kind: 'text', timelineStart: 9, duration: 5, slotId: 'slot-text-2', text: 'Location 2' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-text', kind: 'text', timelineStart: 17, duration: 5, slotId: 'slot-text-3', text: 'Location 3' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-scene-1', type: 'media', label: 'Scene 1', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-scene-2', type: 'media', label: 'Scene 2', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-scene-3', type: 'media', label: 'Scene 3', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-text-1', type: 'text', label: 'Location 1 name', required: true, defaultValue: 'Location 1' },
      { id: 'slot-text-2', type: 'text', label: 'Location 2 name', required: true, defaultValue: 'Location 2' },
      { id: 'slot-text-3', type: 'text', label: 'Location 3 name', required: true, defaultValue: 'Location 3' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Creator: Talking Head ===
  {
    id: 'tpl-talking-head-16x9',
    title: 'Talking Head',
    description: 'Single-subject interview with lower-third name caption. 16:9.',
    category: 'Creator',
    subcategory: 'Interview',
    tags: ['interview', 'talking-head', 'speech', 'presentation', '16x9'],
    thumbnailUrl: thumbnailUrlFor('tpl-talking-head-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 20,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-subject', 'video', 'Subject'),
        buildTrack('tr-text', 'text', 'Lower Third'),
      ],
      clips: [
        buildClip({ id: 'clip-sub', trackId: 'tr-subject', kind: 'video', timelineStart: 0, duration: 20, slotId: 'slot-subject-video' }),
        buildClip({ id: 'clip-name', trackId: 'tr-text', kind: 'text', timelineStart: 2, duration: 6, slotId: 'slot-name', text: 'Speaker Name' }),
        buildClip({ id: 'clip-title', trackId: 'tr-text', kind: 'text', timelineStart: 2.5, duration: 5.5, slotId: 'slot-title', text: 'Title / Role' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-subject-video', type: 'media', label: 'Subject video', required: true, acceptedKinds: ['video'] },
      { id: 'slot-name', type: 'text', label: 'Speaker name', required: true, defaultValue: 'Speaker Name' },
      { id: 'slot-title', type: 'text', label: 'Speaker title', required: false, defaultValue: 'Title / Role' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Business: Promo Announcement ===
  {
    id: 'tpl-promo-announcement-1x1',
    title: 'Promo Announcement',
    description: 'Square promo card with bold headline + CTA. 8 seconds, 1:1.',
    category: 'Business',
    subcategory: 'Promo',
    tags: ['promo', 'announcement', 'square', 'marketing', 'sale'],
    thumbnailUrl: thumbnailUrlFor('tpl-promo-announcement-1x1'),
    aspectRatio: '1:1',
    width: 1080,
    height: 1080,
    fps: 30,
    duration: 8,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-bg', 'video', 'Background'),
        buildTrack('tr-text', 'text', 'Headline'),
      ],
      clips: [
        buildClip({ id: 'clip-bg', trackId: 'tr-bg', kind: 'image', timelineStart: 0, duration: 8, slotId: 'slot-bg' }),
        buildClip({ id: 'clip-headline', trackId: 'tr-text', kind: 'text', timelineStart: 0.5, duration: 7, slotId: 'slot-headline', text: 'BIG ANNOUNCEMENT' }),
        buildClip({ id: 'clip-cta', trackId: 'tr-text', kind: 'text', timelineStart: 4, duration: 4, slotId: 'slot-cta', text: 'Shop now →' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-bg', type: 'media', label: 'Background image', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-headline', type: 'text', label: 'Headline', required: true, defaultValue: 'BIG ANNOUNCEMENT' },
      { id: 'slot-cta', type: 'text', label: 'Call to action', required: true, defaultValue: 'Shop now →' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Visual Styles: Slideshow ===
  {
    id: 'tpl-slideshow-16x9',
    title: 'Slideshow',
    description: 'Photo slideshow with smooth transitions. 16:9, 5 photos × 4s.',
    category: 'Visual Styles',
    subcategory: 'Slideshow',
    tags: ['slideshow', 'photos', 'transitions', 'memories', '16x9'],
    thumbnailUrl: thumbnailUrlFor('tpl-slideshow-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 20,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-photos', 'video', 'Photos'),
      ],
      clips: [
        buildClip({ id: 'clip-p1', trackId: 'tr-photos', kind: 'image', timelineStart: 0, duration: 4, slotId: 'slot-photo-1' }),
        buildClip({ id: 'clip-p2', trackId: 'tr-photos', kind: 'image', timelineStart: 4, duration: 4, slotId: 'slot-photo-2' }),
        buildClip({ id: 'clip-p3', trackId: 'tr-photos', kind: 'image', timelineStart: 8, duration: 4, slotId: 'slot-photo-3' }),
        buildClip({ id: 'clip-p4', trackId: 'tr-photos', kind: 'image', timelineStart: 12, duration: 4, slotId: 'slot-photo-4' }),
        buildClip({ id: 'clip-p5', trackId: 'tr-photos', kind: 'image', timelineStart: 16, duration: 4, slotId: 'slot-photo-5' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-photo-1', type: 'media', label: 'Photo 1', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-2', type: 'media', label: 'Photo 2', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-3', type: 'media', label: 'Photo 3', required: true, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-4', type: 'media', label: 'Photo 4', required: false, acceptedKinds: ['image', 'video'] },
      { id: 'slot-photo-5', type: 'media', label: 'Photo 5', required: false, acceptedKinds: ['image', 'video'] },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Creator: Tutorial ===
  {
    id: 'tpl-tutorial-16x9',
    title: 'Tutorial',
    description: 'Step-by-step tutorial with numbered chapter cards. 16:9, 30 seconds.',
    category: 'Creator',
    subcategory: 'Tutorial',
    tags: ['tutorial', 'how-to', 'education', 'steps', 'instructional'],
    thumbnailUrl: thumbnailUrlFor('tpl-tutorial-16x9'),
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    fps: 30,
    duration: 30,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-screen', 'video', 'Screen recording'),
        buildTrack('tr-text', 'text', 'Steps'),
      ],
      clips: [
        buildClip({ id: 'clip-s1', trackId: 'tr-screen', kind: 'video', timelineStart: 0, duration: 10, slotId: 'slot-screen-1' }),
        buildClip({ id: 'clip-s2', trackId: 'tr-screen', kind: 'video', timelineStart: 10, duration: 10, slotId: 'slot-screen-2' }),
        buildClip({ id: 'clip-s3', trackId: 'tr-screen', kind: 'video', timelineStart: 20, duration: 10, slotId: 'slot-screen-3' }),
        buildClip({ id: 'clip-t1', trackId: 'tr-text', kind: 'text', timelineStart: 1, duration: 4, slotId: 'slot-text-1', text: 'Step 1' }),
        buildClip({ id: 'clip-t2', trackId: 'tr-text', kind: 'text', timelineStart: 11, duration: 4, slotId: 'slot-text-2', text: 'Step 2' }),
        buildClip({ id: 'clip-t3', trackId: 'tr-text', kind: 'text', timelineStart: 21, duration: 4, slotId: 'slot-text-3', text: 'Step 3' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-screen-1', type: 'media', label: 'Step 1 screen', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-screen-2', type: 'media', label: 'Step 2 screen', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-screen-3', type: 'media', label: 'Step 3 screen', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-text-1', type: 'text', label: 'Step 1 label', required: true, defaultValue: 'Step 1' },
      { id: 'slot-text-2', type: 'text', label: 'Step 2 label', required: true, defaultValue: 'Step 2' },
      { id: 'slot-text-3', type: 'text', label: 'Step 3 label', required: true, defaultValue: 'Step 3' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },

  // === §6 Music: Music-Driven Montage ===
  {
    id: 'tpl-music-montage-9x16',
    title: 'Music-Driven Montage',
    description: 'Beat-synced vertical montage with music track slot. 15 seconds, 9:16.',
    category: 'Music',
    subcategory: 'Montage',
    tags: ['music', 'beat-sync', 'montage', 'vertical', 'reels'],
    thumbnailUrl: thumbnailUrlFor('tpl-music-montage-9x16'),
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    fps: 30,
    duration: 15,
    timelineData: {
      schemaVersion: 1,
      tracks: [
        buildTrack('tr-video', 'video', 'Video'),
        buildTrack('tr-audio', 'audio', 'Music'),
        buildTrack('tr-text', 'text', 'Lyric'),
      ],
      clips: [
        buildClip({ id: 'clip-v1', trackId: 'tr-video', kind: 'video', timelineStart: 0, duration: 5, slotId: 'slot-video-1' }),
        buildClip({ id: 'clip-v2', trackId: 'tr-video', kind: 'video', timelineStart: 5, duration: 5, slotId: 'slot-video-2' }),
        buildClip({ id: 'clip-v3', trackId: 'tr-video', kind: 'video', timelineStart: 10, duration: 5, slotId: 'slot-video-3' }),
        buildClip({ id: 'clip-audio', trackId: 'tr-audio', kind: 'audio', timelineStart: 0, duration: 15, slotId: 'slot-music' }),
        buildClip({ id: 'clip-lyric', trackId: 'tr-text', kind: 'text', timelineStart: 3, duration: 4, slotId: 'slot-lyric', text: 'Lyric line here' }),
      ],
      markers: [],
    },
    slots: [
      { id: 'slot-video-1', type: 'media', label: 'Clip 1', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-video-2', type: 'media', label: 'Clip 2', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-video-3', type: 'media', label: 'Clip 3', required: true, acceptedKinds: ['video', 'image'] },
      { id: 'slot-music', type: 'audio', label: 'Music track', required: true, acceptedKinds: ['audio'] },
      { id: 'slot-lyric', type: 'text', label: 'Lyric overlay', required: false, defaultValue: 'Lyric line here' },
    ],
    tier: 'free',
    license: { type: 'cc0', commercialUse: true, attributionRequired: false },
    version: 1,
    isBuiltin: true,
  },
];

/**
 * V19 §8: Compute a real ranking score from actual usage metrics.
 *
 * NOT a fake popularity score — uses real DB-stored metrics:
 *   - usageCount (weight: 1.0)
 *   - likeCount (weight: 2.0)
 *   - saveCount (weight: 1.5)
 *   - shareCount (weight: 3.0)
 *   - completionRate (weight: 5.0) — most important signal
 *   - recencyBoost (boost for templates published in last 7 days)
 */
export function computeTemplateRank(metrics: {
  usageCount: number;
  likeCount: number;
  saveCount: number;
  shareCount: number;
  completionRate: number; // 0..1
  publishedAt: Date | null;
}): number {
  const now = Date.now();
  const weekMs = 7 * 24 * 60 * 60 * 1000;
  const recencyBoost = metrics.publishedAt && (now - metrics.publishedAt.getTime()) < weekMs ? 1.5 : 1.0;
  const score = (
    metrics.usageCount * 1.0 +
    metrics.likeCount * 2.0 +
    metrics.saveCount * 1.5 +
    metrics.shareCount * 3.0 +
    metrics.completionRate * 100 * 5.0
  ) * recencyBoost;
  return Math.round(score * 100) / 100;
}
